### ISSUE TITLE
Xcode archive resulting in error

### ISSUE THREAD

**Issue by error-bruno** [alinz/react-native-webview-bridge#134]
This issue just started happening this morning, but when I would go to archive my project, I'm getting a `File/Program node, we can't possibly find a statement parent to this`.

I think it has something to do with Babel, but I thought I would throw it out there to see if anyone else has had the same issue. Full stack trace below:

```
MyApp-gsdfmybbuzoatuadyudywvrhynvn/Build/Intermediates/ArchiveIntermediates/MyApp/BuildProductsPath/Release-iphoneos/MyApp.app
[9:25:38 AM] <START> Building Dependency Graph
[9:25:38 AM] <START> Crawling File System
[9:25:39 AM] <START> find dependencies
[9:25:45 AM] <END>   Crawling File System (7213ms)
[9:25:45 AM] <START> Building in-memory fs for JavaScript
[9:25:45 AM] <END>   Building in-memory fs for JavaScript (254ms)
[9:25:45 AM] <START> Building in-memory fs for Assets
[9:25:45 AM] <END>   Building in-memory fs for Assets (155ms)
[9:25:45 AM] <START> Building Haste Map
[9:25:46 AM] <START> Building (deprecated) Asset Map
[9:25:46 AM] <END>   Building (deprecated) Asset Map (69ms)
[9:25:46 AM] <END>   Building Haste Map (474ms)
[9:25:46 AM] <END>   Building Dependency Graph (8154ms)

/Users/johndoe/code/work/MyApp/node_modules/promise/lib/done.js:10
      throw err;
      ^
Error: /Users/johndoe/code/work/MyApp/node_modules/react-native-webview-bridge/webview-bridge/index.ios.js: File/Program node, we can't possibly find a statement parent to this
    at NodePath.getStatementParent (/Users/johndoe/code/work/MyApp/node_modules/babel-traverse/lib/path/family.js:43:11)
    at PathHoister.getAttachmentPath (/Users/johndoe/code/work/MyApp/node_modules/babel-traverse/lib/path/lib/hoister.js:118:26)
    at PathHoister.run (/Users/johndoe/code/work/MyApp/node_modules/babel-traverse/lib/path/lib/hoister.js:171:25)
    at NodePath.hoist (/Users/johndoe/code/work/MyApp/node_modules/babel-traverse/lib/path/modification.js:292:18)
    at PluginPass.JSXElement (/Users/johndoe/code/work/MyApp/node_modules/babel-plugin-transform-react-constant-elements/lib/index.js:39:16)
    at newFn (/Users/johndoe/code/work/MyApp/node_modules/babel-traverse/lib/visitors.js:301:19)
    at NodePath._call (/Users/johndoe/code/work/MyApp/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/johndoe/code/work/MyApp/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/johndoe/code/work/MyApp/node_modules/babel-traverse/lib/path/context.js:106:12)
TransformError: /Users/johndoe/code/work/MyApp/node_modules/react-native-webview-bridge/webview-bridge/index.ios.js: /Users/johndoe/code/work/MyApp/node_modules/react-native-webview-bridge/webview-bridge/index.ios.js: File/Program node, we can't possibly find a statement parent to this
Command /bin/sh failed with exit code 1
```

**Comment by GuillaumeCisco** [comment]
Did you try to remove `transform-react-constant-elements` from your plugins?
