### ISSUE TITLE
android app crash while run the app

### ISSUE THREAD

**Issue by lalakiyarahul66** [alinz/react-native-webview-bridge#303]
Get run time error and app will be crash.
`E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.textediter, PID: 6385
    java.lang.NoClassDefFoundError: com.github.alinz.reactnativewebviewbridge.WebViewBridgeManager
        at com.github.alinz.reactnativewebviewbridge.WebViewBridgePackage.createViewManagers(WebViewBridgePackage.java:21)
        at com.facebook.react.ReactInstanceManager.getOrCreateViewManagers(ReactInstanceManager.java:782)
        at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:184)
        at com.facebook.react.CoreModulesPackage.getModule(CoreModulesPackage.java:152)
        at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:122)
        at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:110)
        at com.facebook.react.bridge.ModuleHolder.create(ModuleHolder.java:188)
        at com.facebook.react.bridge.ModuleHolder.getModule(ModuleHolder.java:153)
        at com.facebook.react.bridge.NativeModuleRegistry.getModule(NativeModuleRegistry.java:148)
        at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:479)
        at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:466)
        at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:31)
        at com.facebook.react.ReactInstanceManager.attachRootViewToInstance(ReactInstanceManager.java:1054)
        at com.facebook.react.ReactInstanceManager.setupReactContext(ReactInstanceManager.java:1012)
        at com.facebook.react.ReactInstanceManager.access$1400(ReactInstanceManager.java:125)
        at com.facebook.react.ReactInstanceManager$5$2.run(ReactInstanceManager.java:972)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
        at android.os.Looper.loop(Looper.java:148)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
        at java.lang.Thread.run(Thread.java:818)`

**Comment by betterfuture009** [comment]
Same issue. What's the solve way?

**Comment by AngeeelD** [comment]
Any idea on how to solve?

**Comment by washim-suuni** [comment]
hey there any idea how to solve it

**Comment by washim-suuni** [comment]
@AngeeelD 
@lalakiyarahul66 
@livefuture009

**Comment by softwareonair** [comment]
same here.

**Comment by ArthurSampaio** [comment]
same here, rn > 0.6

**Comment by MahmoudShaeer** [comment]
same here :/

**Comment by 92sajid110** [comment]
App closes after adding this library
