### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by gn02394847** [alinz/react-native-webview-bridge#94]
OPPO Find 7a X9006 
Android 4.3

java.lang.NoSuchMethodError: android.webkit.WebView.evaluateJavascript
	at com.github.alinz.reactnativewebviewbridge.WebViewBridgeManager.injectBridgeScript(WebViewBridgeManager.java:67)
	at com.github.alinz.reactnativewebviewbridge.WebViewBridgeManager.receiveCommand(WebViewBridgeManager.java:38)
	at com.github.alinz.reactnativewebviewbridge.WebViewBridgeManager.receiveCommand(WebViewBridgeManager.java:12)
	at com.facebook.react.uimanager.NativeViewHierarchyManager.dispatchCommand(NativeViewHierarchyManager.java:597)
	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchCommandOperation.execute(UIViewOperationQueue.java:238)
	at com.facebook.react.uimanager.UIViewOperationQueue$2.run(UIViewOperationQueue.java:740)
	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:804)
	at com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame(GuardedChoreographerFrameCallback.java:32)
	at com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:125)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:747)
	at android.view.Choreographer.doCallbacks(Choreographer.java:562)
	at android.view.Choreographer.doFrame(Choreographer.java:531)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
	at android.os.Handler.handleCallback(Handler.java:730)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5166)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:561)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by gn02394847** [comment]
https://github.com/evgenyneu/js-evaluator-for-android
